# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
workflows:
   version: 2
   hourly:
     triggers:
       - schedule:
           cron: "0 * * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - run-lighthouse

jobs:
  run-lighthouse:
    machine: true
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm i -g lighthouse-graphite@0.0.5 --no-progress
      - run: lighthouse-graphite "$URL" --runs=7 --graphite-host="$GRAPHITE_HOST" --graphite-prefix="$GRAPHITE_PREFIX" --function-blacklist=min,max,mean --metrics-blacklist=dom-size,pwa-score,accessibility-score,best-practices-score,seo-score
